server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cache: DEBUG

spring.jpa.show-sql: true

spring:
  profiles:
    active: dev

jwt:
  secret: YouWillNeverWalkAloneAccessLiverpool
  refresh: YouWillNeverWalkAloneRefreshLiverpool
  access-expire-time: 259_200_000 # 60? (?? ?, 3?? ??)
  refresh-expire-time: 259_200_000  # 3? (259,200,000 ???)

---

spring:
  config:
    activate:
      on-profile: product

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://raccon-db.crmgsw8ccq8f.ap-northeast-2.rds.amazonaws.com:5432/raccon?currentSchema=product
    username: postgres
    password: racconpostgres
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  flyway:
    user: postgres
    password: racconpostgres
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

spring.jpa.show-sql: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: postgres
    password: racconpostgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://raccon-db.crmgsw8ccq8f.ap-northeast-2.rds.amazonaws.com:5432/raccon?currentSchema=dev
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  flyway:
    user: postgres
    password: racconpostgres
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

spring.jpa.show-sql: true

---